---
title: profanadores
timezone: UTC
collections:
  posts:
    title: Postagens
    output: true
  uploads:
    title: Uploads
    output: true
=======
# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            profanadores
tagline:          registro de desenvolvimento
description:      "Metroidvania livremente baseado na obra de H. P. Lovecraft"
url:              https://macalango.github.io/
baseurl:          /profanadores/

author:
  name:           'Laureano Macalango'
  url:            https://remote.com/macalango

paginate:         5

# Custom vars
version:          1.0.1
