# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            PROFANADORES
tagline:          registro de desenvolvimento
description:      "A two-column black theme with a scrolling sidebar. Ideal for sites requiring a master-detail layout, e.g. documentation, cheatsheets, lyrics, notes..."
url:              https://macalango.github.io/
baseurl:          /devlog/

author:
  name:           'Laureano Macalango'
  url:            https://remote.com/macalango

paginate:         5

# Custom vars
version:          1.0.1

github:           https://github.com/macalango
  repo:           macalango/macalango.github.io
