---
title: profanadores
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
- jekyll-paginate
- jekyll-gist
- jekyll-github-metadata
highlighter: rouge
permalink: pretty
tagline: registro de desenvolvimento
description: Um Metroidvania livremente baseado na obra de H. P. Lovecraft
url: https://macalango.github.io/
baseurl: "/profanadores/"
author:
  name: Laureano Macalango
  url: https://remote.com/macalango
paginate: 5
version: 1.0.1
